
version: '3.8'

services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - backend

  eurekaserver:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  apigateway:
    build: ./apiGateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eurekaserver
    networks:
      - backend

  userservice:
    build: ./userService
    container_name: user-service
    restart: on-failure

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/multirestaurantordering
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eurekaserver
    networks:
      - backend

  restaurantservice:
    build: ./restaurantService
    container_name: restaurant-service
    restart: on-failure

    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/multirestaurantordering
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eurekaserver
    networks:
      - backend

  orderservice:
    build: ./orderService
    container_name: order-service
    restart: on-failure

    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/multirestaurantordering
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eurekaserver
    networks:
      - backend

  deliveryservice:
    build: ./delivery
    container_name: delivery-service
    restart: on-failure

    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/multirestaurantordering
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eurekaserver
    networks:
      - backend

networks:
  backend:
    driver: bridge
