apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryservice
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice
          image: hvrdummy123/deliveryservice:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
spec:
  selector:
    app: deliveryservice
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
